"""Summarizer API routes - MVC View layer (only HTTP request/response handling)."""

from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Query

from src.shared.constant.enums import CoTMode
from src.shared.utils import get_logger
from ..common import get_api_key, summarizer_service
from ..schemas import (
    SummarizeRequest, SummaryResponse, AddTurnRequest
)

logger = get_logger(__name__)

router = APIRouter(prefix="/api/v1/agent", tags=["Summarizer"])


@router.post("/{agent_id}/summarizer/summarize", response_model=SummaryResponse)
async def summarize_conversation(
    agent_id: str,
    request: SummarizeRequest,
    _api_key: str = Depends(get_api_key)  # Authentication dependency (value not used)
):
    """
    Summarize conversation records using the Summarizer agent.

    This endpoint now focuses on user questions and handles long conversations
    by truncating and optimizing the input.

    Args:
        agent_id: The agent's unique identifier
        request: Summarization request with conversation records
        _api_key: Authentication dependency (value not used, required for auth check)

    Returns:
        Summary response with metadata about truncation
    """
    try:
        execution_mode = request.use_cot.value if isinstance(request.use_cot, CoTMode) else str(request.use_cot)
        result = summarizer_service.summarize_conversation(
            agent_id=agent_id,
            conversation_records=request.conversation_records,
            execution_mode=execution_mode,
            use_few_shots=request.use_few_shots
        )
        
        if "error" in result:
            logger.warning(f"Agent {agent_id} summarize error: {result['error']}")
            raise HTTPException(status_code=400, detail=result["error"])
        
        return SummaryResponse(**result)
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Failed to summarize conversation for agent {agent_id}: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"Failed to summarize conversation: {str(e)}")


@router.get("/{agent_id}/summarizer/history")
async def get_summary_history(
    agent_id: str,
    _api_key: str = Depends(get_api_key)  # Authentication dependency (value not used)
):
    """
    Get the history of summaries generated by this agent (legacy endpoint).

    Args:
        agent_id: The agent's unique identifier
        _api_key: Authentication dependency (value not used, required for auth check)

    Returns:
        List of summary metadata
    """
    try:
        history = summarizer_service.get_summary_history(agent_id)
        return {
            "summaries": history,
            "total_summaries": len(history)
        }
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))
    except Exception as e:
        logger.error(f"Failed to get summary history for agent {agent_id}: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"Failed to get summary history: {str(e)}")


# ============================================================================
# Conversation Management Endpoints
# ============================================================================

@router.post("/{agent_id}/summarizer/conversation")
async def create_conversation(
    agent_id: str,
    conversation_id: Optional[str] = None,
    _api_key: str = Depends(get_api_key)  # Authentication dependency (value not used)
):
    """
    Create a new conversation for the Summarizer agent.
    
    A conversation contains multiple turns (user + assistant exchanges) and can have a summary.
    
    Args:
        agent_id: The agent's unique identifier
        conversation_id: Optional conversation ID. If None, auto-generate.
        _api_key: Authentication dependency (value not used, required for auth check)
    
    Returns:
        Conversation creation result with conversation_id
    """
    try:
        conv_id = summarizer_service.create_conversation(agent_id, conversation_id=conversation_id)
        return {
            "conversation_id": conv_id,
            "message": f"Conversation '{conv_id}' created successfully"
        }
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))
    except Exception as e:
        logger.error(f"Failed to create conversation: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"Failed to create conversation: {str(e)}")


@router.post("/{agent_id}/summarizer/conversation/{conversation_id}/turn")
async def add_turn(
    agent_id: str,
    conversation_id: str,
    request: AddTurnRequest,
    _api_key: str = Depends(get_api_key)  # Authentication dependency (value not used)
):
    """
    Add a turn (user message + assistant response) to a conversation.
    
    Each turn represents one exchange: user asks a question, assistant responds.
    A conversation can contain multiple turns.
    
    Args:
        agent_id: The agent's unique identifier
        conversation_id: The conversation ID
        request: Request body with user_message and assistant_message
        _api_key: Authentication dependency (value not used, required for auth check)
    
    Returns:
        Success message with turn_index
    """
    try:
        result = summarizer_service.add_turn(
            agent_id=agent_id,
            conversation_id=conversation_id,
            user_message=request.user_message,
            assistant_message=request.assistant_message
        )
        
        if "error" in result:
            raise HTTPException(status_code=400, detail=result["error"])
        
        return result
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Failed to add turn: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"Failed to add turn: {str(e)}")


@router.get("/{agent_id}/summarizer/conversations")
async def list_conversations(
    agent_id: str,
    _api_key: str = Depends(get_api_key)  # Authentication dependency (value not used)
):
    """
    List all conversations for the Summarizer agent.
    
    Args:
        agent_id: The agent's unique identifier
        _api_key: Authentication dependency (value not used, required for auth check)
    
    Returns:
        List of conversation metadata
    """
    try:
        conversations = summarizer_service.list_conversations(agent_id)
        return {
            "conversations": conversations,
            "total_count": len(conversations)
        }
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))
    except Exception as e:
        logger.error(f"Failed to list conversations: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"Failed to list conversations: {str(e)}")


@router.get("/{agent_id}/summarizer/conversation/{conversation_id}")
async def get_conversation(
    agent_id: str,
    conversation_id: str,
    turn: Optional[int] = Query(None, description="Turn number (0-based index). If not specified, returns all turns."),
    _api_key: str = Depends(get_api_key)  # Authentication dependency (value not used)
):
    """
    Get detailed information about a specific conversation.

    If turn is not specified, returns all turns and the summary (if available) for the conversation.
    If turn is specified, returns only the specified turn.

    Args:
        agent_id: The agent's unique identifier
        conversation_id: The conversation ID
        turn: Optional turn number (0-based index). If None, returns all turns.
        _api_key: Authentication dependency (value not used, required for auth check)

    Returns:
        Conversation details including turns and summary, or specific turn data
    """
    try:
        return summarizer_service.get_conversation(agent_id, conversation_id, turn=turn)
    except ValueError as e:
        if turn is not None:
            raise HTTPException(status_code=404, detail=f"Conversation '{conversation_id}' or turn {turn} not found")
        else:
            raise HTTPException(status_code=404, detail=f"Conversation '{conversation_id}' not found")
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Failed to get conversation: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"Failed to get conversation: {str(e)}")


@router.delete("/{agent_id}/summarizer/conversation/{conversation_id}")
async def delete_conversation(
    agent_id: str,
    conversation_id: str,
    _api_key: str = Depends(get_api_key)  # Authentication dependency (value not used)
):
    """
    Delete a specific conversation.
    
    This permanently removes the conversation, including all its turns and summary.
    
    Args:
        agent_id: The agent's unique identifier
        conversation_id: The conversation ID to delete
        _api_key: Authentication dependency (value not used, required for auth check)
    
    Returns:
        Success message
    """
    try:
        deleted = summarizer_service.delete_conversation(agent_id, conversation_id)
        
        if not deleted:
            raise HTTPException(status_code=404, detail=f"Conversation '{conversation_id}' not found")
        
        return {
            "message": f"Conversation '{conversation_id}' deleted successfully",
            "conversation_id": conversation_id
        }
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Failed to delete conversation: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"Failed to delete conversation: {str(e)}")


@router.post("/{agent_id}/summarizer/conversation/{conversation_id}/summarize", response_model=SummaryResponse)
async def summarize_conversation_by_id(
    agent_id: str,
    conversation_id: str,
    use_few_shots: bool = Query(default=True, description="Whether to use few-shot examples"),
    custom_few_shots: Optional[str] = Query(default=None, description="Optional custom few-shot examples"),
    _api_key: str = Depends(get_api_key)  # Authentication dependency (value not used)
):
    """
    Generate a summary for a specific conversation.

    This summarizes all turns in the conversation and stores the summary with the conversation.

    Args:
        agent_id: The agent's unique identifier
        conversation_id: The conversation ID to summarize
        use_few_shots: Whether to use few-shot examples (default: True)
        custom_few_shots: Optional custom few-shot examples
        _api_key: Authentication dependency (value not used, required for auth check)

    Returns:
        Summary response with summary text and metadata
    """
    try:
        result = summarizer_service.summarize_conversation_by_id(
            agent_id=agent_id,
            conversation_id=conversation_id,
            use_few_shots=use_few_shots,
            custom_few_shots=custom_few_shots
        )
        
        if "error" in result:
            raise HTTPException(status_code=400, detail=result["error"])
        
        return SummaryResponse(**result)
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Failed to summarize conversation: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"Failed to summarize conversation: {str(e)}")
